stages:
  - test

default:
  tags:
    - docker-exec
  services:
    - name: postgres:13
    - name: dnhsoft/mysql-utf8:5.7-mb4
      alias: mysql
  before_script:
    - |
        curl "https://api.github.com/repos/qorelanguage/${REPO_NAME}/statuses/${CI_COMMIT_SHA}" \
        -X POST -u omusil24:${GITHUB_ACCESS_TOKEN} -H "Content-Type: application/json" \
        -d "{\"state\": \"pending\", \"context\": \"${REPO_NAME}\", \"description\": \"Gitlab CI\", \"target_url\": \"${CI_JOB_URL}\"}"
    - set +e
    - unset QORE_DB_CONNSTR_FREETDS # temp disable freetds testing

variables:
  REPO_NAME: qore
  POSTGRES_PASSWORD: omq
  TZ: 'Europe/Prague'
  PGTZ: 'Europe/Prague'
  TDSVER: "7.3"
  MYSQL_DATABASE: omq
  MYSQL_ROOT_PASSWORD: omq
  QORE_DB_CONNSTR: 'pgsql:postgres/omq@postgres(UTF8)%postgres{timezone=Europe/Prague}'
  QORE_DB_CONNSTR_FREETDS: 'freetds:test/test@mssql%192.168.20.93:1433'
  QORE_DB_CONNSTR_MYSQL: 'mysql:root/omq@omq(UTF8)%mysql'
  QORE_DB_CONNSTR_ORACLE: 'oracle:omquser/omquser@xbox%xbox:1521'
  QORE_DB_CONNSTR_PGSQL: 'pgsql:postgres/omq@postgres(UTF8)%postgres{timezone=Europe/Prague}'

test-ubuntu:
  stage: test
  image: $CI_REGISTRY/infrastructure/qore-test-base/qore-test-base:develop
  script:
    - |
        if test/docker_test/test-ubuntu.sh; then
          curl "https://api.github.com/repos/qorelanguage/${REPO_NAME}/statuses/${CI_COMMIT_SHA}" \
            -X POST -u omusil24:${GITHUB_ACCESS_TOKEN} -H "Content-Type: application/json" \
            -d "{\"state\": \"success\", \"context\": \"${REPO_NAME}\", \"description\": \"Gitlab CI\", \"target_url\": \"${CI_JOB_URL}\"}"
          exit 0
        else
          curl "https://api.github.com/repos/qorelanguage/${REPO_NAME}/statuses/${CI_COMMIT_SHA}" \
            -X POST -u omusil24:${GITHUB_ACCESS_TOKEN} -H "Content-Type: application/json" \
            -d "{\"state\": \"failure\", \"context\": \"${REPO_NAME}\", \"description\": \"Gitlab CI\", \"target_url\": \"${CI_JOB_URL}\"}"
          exit 1
        fi

test-alpine:
  stage: test
  image: $CI_REGISTRY/infrastructure/qore-test-base/qore-test-base:develop-alpine
  script:
    - |
        if test/docker_test/test-alpine.sh; then
          curl "https://api.github.com/repos/qorelanguage/${REPO_NAME}/statuses/${CI_COMMIT_SHA}" \
            -X POST -u omusil24:${GITHUB_ACCESS_TOKEN} -H "Content-Type: application/json" \
            -d "{\"state\": \"success\", \"context\": \"${REPO_NAME}\", \"description\": \"Gitlab CI\", \"target_url\": \"${CI_JOB_URL}\"}"
          exit 0
        else
          curl "https://api.github.com/repos/qorelanguage/${REPO_NAME}/statuses/${CI_COMMIT_SHA}" \
            -X POST -u omusil24:${GITHUB_ACCESS_TOKEN} -H "Content-Type: application/json" \
            -d "{\"state\": \"failure\", \"context\": \"${REPO_NAME}\", \"description\": \"Gitlab CI\", \"target_url\": \"${CI_JOB_URL}\"}"
          exit 1
        fi
