#.\"
.\" MAN PAGE COMMENTS to
.\"
.\"	Chet Ramey
.\"	Information Network Services
.\"	Case Western Reserve University
.\"	chet@po.CWRU.Edu
.\"
.\"	Last Change: Sat Jun 26 14:26:44 EDT 2004
.\"
.\" bash_builtins, strip all but Built-Ins section
.TH QORE 1 "2014 June 22" "Qore 0.8.11"
.\"
.\" There's some problem with having a `@'
.\" in a tagged paragraph with the BSD man macros.
.\" It has to do with `@' appearing in the }1 macro.
.\" This is a problem on 4.3 BSD and Ultrix, but Sun
.\" appears to have fixed it.
.\" If you're seeing the characters
.\" `@u-3p' appearing before the lines reading
.\" `possible-hostname-completions
.\" and `complete-hostname' down in READLINE,
.\" then uncomment this redefinition.
.\"
.de }1
.ds ]X \&\\*(]B\\
.nr )E 0
.if !"\\$1"" .nr )I \\$1n
.}f
.ll \\n(LLu
.in \\n()Ru+\\n(INu+\\n()Iu
.ti \\n(INu
.ie !\\n()Iu+\\n()Ru-\w\\*(]Xu-3p \{\\*(]X
.br\}
.el \\*(]X\h|\\n()Iu+\\n()Ru\c
.}f
..
.\"
.\" File Name macro.  This used to be `.PN', for Path Name,
.\" but Sun doesn't seem to like that very much.
.\"
.de FN
\fI\|\\$1\|\fP
..
.SH NAME
qore \- Interpreter for the Qore Programming Language
.SH SYNOPSIS
.B qore
[options(s)]...
[program file]
.SH COPYRIGHT
.if n Qore is Copyright (C) 2003 - 2014 David Nichols.
.if t Qore is Copyright \(co 2003 - 2014 David Nichols.
.SH DESCRIPTION
\fBQore\fR is a modular, multi-threaded, SQL-integrated weakly-typed scripting language with procedural and object-oriented features, powerful and easy-to-use data types, structures, and operators, a clean and easy-to-lean/read syntax.
.SH OPTIONS
When \fBqore\fR is invoked it
interprets the following options:
.PP
.PD 0
.TP 10
.B \-d,  \-\-debug=arg
sets debugging level (higher number = more output).  Only available with debug builds.
.TP
.B \-t, \-\-trace
turns on function tracing.  Only available with debug builds.
.TP
.B \-h, \-\-help
shows the help text.
.TP
.B \-c, \-\-charset=arg
sets default character set encoding.
.TP
.B \-e, \-\-exec=arg
allows a qore program to be specified on the command-line.
.TP
.B \-x, \-\-exec-class[=arg]
instantiate a class with the same name as the file name, override class name with the optional argument.  Also sets --no-top-level for more pure object-oriented coding.
.TP
.B \-m, \-\-show-module-errors
shows any errors related to qore module loading and/or initilization.
.TP
.B \-\-show\-charsets
displays the list of known character sets.
.TP
.B \-\-show\-aliases
displays the list of character sets aliases.
.TP
.B \-V, \-\-version
shows version information for the invoked instance of
.B qore
on the standard output and exits successfully.
.PD
.SH PARSE OPTIONS
Parse options interpreted by \fBqore\fR:
.PP
.PD 0
.TP 10
.B \-G, \-\-no\-global\-vars
makes global variable definitions illegal
.TP
.B \-S, \-\-no\-subroutine\-def
makes subroutine definitions illegal
.TP
.B \-T, \-\-no\-threads
makes thread operations illegal
.TP
.B \-L, \-\-no\-top\-level
makes top-level statements illegal
.TP
.B \-C, \-\-no\-class\-defs
makes class definitions illegal
.TP
.B \-D, \-\-no\-namespace\-defs
makes namespace declarations illegal
.TP
.B \-E, \-\-no\-external\-process
makes access to external processes illegal
.TP
.B \-P, \-\-no\-process\-control
makes process control illegal (fork(), exit(), etc)
.TP
.B \-F, \-\-no\-constant\-defs
makes constant definitions illegal
.TP
.B \-N, \-\-no\-new
makes using the "new" operator illegal
.TP
.B \-I, \-\-no\-child\-restrictions
do not restrict subprograms' parse options
.TP
.B \-O, \-\-require\-our
requires global variables to be declared with "our"
.PD
.PP
.SH FILES
.PD 0
.TP
.FN /usr/bin/qore
The \fBqore\fP executable
.PD
.PP
.SH AUTHORS
David Nichols (qore)
.br
david@qore.org
.PD
.PP
Marian Bonda (man page)
.br
marian_bonda@users.sourceforge.net
.PD
.SH BUG REPORTS
If you find a bug in
.B qore,
you should report it.  But first, you should
make sure that it really is a bug, and that it appears in the latest
version of
.BR qore .
The latest version is always available at
\fIhttp://qore.org/\fP.
.PD
.PP
ALL bug reports should include:
.PP
.PD 0
.TP 20
The version number of \fBqore\fR
.TP
The hardware and operating system
.TP
The compiler used to compile
.TP
A description of the bug behaviour
.TP
A short script or `recipe' which exercises the bug
.PD
.PP
Comments and bug reports concerning
this manual page should be directed to
.IR marian_bonda@users.sourceforge.net .
