// logger module single compilation unit

#include "logger-module.cpp"
#include "QoreLoggerLevel.cpp"
#include "QC_LoggerLevel.cpp"
#include "QoreLoggerPattern.cpp"
#include "QC_LoggerPattern.cpp"
#include "QoreLoggerEvent.cpp"
#include "QC_LoggerEvent.cpp"
#include "QC_LoggerLayout.cpp"
#include "QoreLoggerLayoutPattern.cpp"
#include "QC_LoggerLayoutPattern.cpp"
#include "QC_LoggerFilter.cpp"
#include "QoreLoggerAppender.cpp"
#include "QC_LoggerAppender.cpp"
#include "QoreLoggerAppenderQueue.cpp"
#include "QC_LoggerAppenderQueue.cpp"
#include "QoreLoggerAppenderWithLayout.cpp"
#include "QC_LoggerAppenderWithLayout.cpp"
#include "QoreLoggerAppenderFile.cpp"
#include "QC_LoggerAppenderFile.cpp"
#include "QC_LoggerInterface.cpp"
#include "QoreLogger.cpp"
#include "QC_Logger.cpp"

