// logger module single compilation unit

#include "logger-module.cpp"
#include "QoreLoggerLevelBase.cpp"
#include "QC_LoggerLevelBase.cpp"
#include "QoreLoggerPattern.cpp"
#include "QC_LoggerPattern.cpp"
#include "QoreLoggerEvent.cpp"
#include "QC_LoggerEvent.cpp"
#include "QC_LoggerLayout.cpp"
#include "QoreLoggerLayoutPattern.cpp"
#include "QC_LoggerLayoutPattern.cpp"
#include "QC_LoggerFilter.cpp"
#include "QoreLoggerAppender.cpp"
#include "QC_LoggerAppender.cpp"
#include "QoreLoggerAppenderQueue.cpp"
#include "QC_LoggerAppenderQueue.cpp"
#include "QoreLoggerAppenderWithLayout.cpp"
#include "QC_LoggerAppenderWithLayout.cpp"
