#ifndef _QORE_VERSION_H
#define _QORE_VERSION_H
#define QORE_VERSION_MAJOR @VERSION_MAJOR@
#define QORE_VERSION_MINOR @VERSION_MINOR@
#define QORE_VERSION_SUB @VERSION_SUB@
#define QORE_VERSION_PATCH @VERSION_PATCH@
#if @VERSION_PATCH@ == 0
#define QORE_VERSION "@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_SUB@"
#else
#define QORE_VERSION "@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_SUB@.@VERSION_PATCH@"
#endif
#define QORE_VERSION_CODE @VERSION_MINOR@@VERSION_FORMATTED_SUB@
#endif
