#ifndef _QORE_VERSION_H
#define _QORE_VERSION_H
#define QORE_VERSION_MAJOR @VERSION_MAJOR@
#define QORE_VERSION_MINOR @VERSION_MINOR@
#define QORE_VERSION_SUB @VERSION_SUB@
#define QORE_VERSION "@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_SUB@"
#define QORE_VERSION_CODE @VERSION_MAJOR@@VERSION_MINOR@
#endif
