#ifndef _QORE_VERSION_H
#define _QORE_VERSION_H
#define QORE_VERSION_MAJOR @VERSION_MAJOR@
#define QORE_VERSION_MINOR @VERSION_MINOR@
#define QORE_VERSION_SUB @VERSION_SUB@
#define QORE_VERSION_PATCH @VERSION_PATCH@
#define QORE_VERSION "@VERSION@"
#define QORE_VERSION_CODE @VERSION_MAJOR@@VERSION_FORMATTED_MINOR@@VERSION_FORMATTED_SUB@
#endif
